#!/usr/bin/env python3
"""Forge banner launcher installer/uninstaller (fg-a10904).

A Claude Code SessionStart hook cannot paint the user's terminal: its
stdout becomes model context, not terminal output. That is why
hooks/hooks.json no longer wires hooks/scripts/banner.sh into SessionStart
(root cause discovered 2026-07-18: the örn banner rendered into the model's
context every session and the user never saw a single pixel of it). The only
way to actually show the banner in a terminal is an OPT-IN shell launcher
shim that intercepts the `claude` command, prints the banner to the real
terminal, and then hands off to the real CLI. This module installs,
upgrades, uninstalls, and reports the status of that shim across every shell
surface Windows exposes. Invoked by commands/banner.md (`/forge:banner`).

Shell surfaces covered, per the live-debug ground truth captured in
.forge/queue/tasks/fg-a10904-banner-launcher.md (2026-07-18, user's machine):

  - PowerShell ($PROFILE, both `powershell` and `pwsh` if installed): a
    marker-guarded `claude` function that invokes `banner.py --anim`
    (fg-a10905) DIRECTLY -- never piped through `| Out-Host`, which would
    buffer output and defeat the animation's cursor-up redraws -- skips
    -p/--print, try/catch fail-open to a plain launch. Detects and upgrades
    a hand-rolled block using the same markers (the 2026-07-18 hand fix
    used this exact marker text).
  - cmd.exe: a shim dir (claude.bat) is NOT sufficient on its own -- if the
    real claude.exe's directory sits on the SYSTEM PATH it shadows a
    user-PATH shim, because cmd searches the system PATH first. The working
    mechanism is a doskey macro loaded via the HKCU AutoRun registry value
    (doskey only expands interactively, so `cmd /c` and scripts are
    unaffected "for free"). AutoRun is created if absent and chained
    ("existing & ours") if something else already occupies it.
  - bash/zsh (~/.bashrc, ~/.zshrc), when present: an equivalent function.

Out of scope, documented rather than handled: Win+R "claude" (the Run
dialog) launches claude.exe directly and bypasses every shim below -- there
is no interception point for that path.

Stdlib only, per the project constitution. Every shell-surface transform is
a pure, independently testable unit (marker-block upsert/remove, AutoRun
chaining) that takes plain strings and does no I/O; the thin wrappers around
them are the only things that touch the real filesystem or registry, and
registry access is behind get_autorun_value/set_autorun_value so tests can
stub it out without ever touching HKCU.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

try:
    import winreg  # type: ignore[import-not-found]
except ImportError:  # pragma: no cover - exercised only on non-Windows
    winreg = None

# Same-process import of the patch engine (bm-banner-takeover): install/
# restore now run the binary patch directly, in this Python process, rather
# than shelling out to a second `python banner.py` invocation. The generated
# SHIMS still shell out to `banner.py --recheck-patch` at every `claude`
# launch (see build_*_body below) -- that one has to be a subprocess because
# it runs long after this installer process has exited.
sys.path.insert(0, str(Path(__file__).resolve().parent))
import banner as banner_patch  # noqa: E402


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

MARKER_START = "# >>> forge örn banner >>>"
MARKER_END = "# <<< forge örn banner <<<"

SHIM_DIRNAME = os.path.join(".local", "shims")
CLAUDE_BAT_NAME = "claude.bat"
AUTORUN_CMD_NAME = "forge-autorun.cmd"

REGISTRY_KEY_PATH = r"Software\Microsoft\Command Processor"
REGISTRY_VALUE_NAME = "AutoRun"

# Identifying tags written into the generated shim files, so uninstall only
# ever deletes files it recognizes as its own (never an unrelated user file
# that happens to share the name).
FORGE_BAT_TAG = ("REM forge-banner-shim (fg-a10904) -- regenerated by "
                  "/forge:banner install, safe to delete")
FORGE_AUTORUN_TAG = ("REM forge-banner-autorun (fg-a10904) -- regenerated by "
                      "/forge:banner install, safe to delete")


# ---------------------------------------------------------------------------
# Resolution: claude CLI, python interpreter, banner.py -- all resolved at
# install time, never hardcoded (machines differ: npm prefix, nvm, a
# WindowsApps app-execution-alias stub shadowing the real Python on PATH).
# ---------------------------------------------------------------------------

def resolve_claude_cli_path():
    """Absolute path to the real `claude` CLI, or None if not found."""
    if os.name == "nt":
        try:
            result = subprocess.run(["where", "claude"], capture_output=True,
                                     text=True, timeout=10)
            if result.returncode == 0:
                for line in result.stdout.splitlines():
                    line = line.strip()
                    if line:
                        return line
        except Exception:
            pass
    return shutil.which("claude")


def _python_actually_runs(path):
    try:
        result = subprocess.run([path, "--version"], capture_output=True,
                                 text=True, timeout=10)
        return result.returncode == 0
    except Exception:
        return False


def _is_windowsapps_stub(path):
    return "WindowsApps" in str(path)


def resolve_python_interpreter():
    """Absolute path to a working CPython interpreter, preferring a real
    install over the Windows Store app-execution-alias stub -- a bare
    python.exe under .../WindowsApps/ that can precede the real interpreter
    on PATH and, invoked directly, opens the Store rather than running
    (ground truth item 3). Verified with --version, never assumed."""
    candidates = []
    if os.name == "nt":
        try:
            result = subprocess.run(["where", "python"], capture_output=True,
                                     text=True, timeout=10)
            if result.returncode == 0:
                candidates.extend(
                    line.strip() for line in result.stdout.splitlines()
                    if line.strip()
                )
        except Exception:
            pass
    else:
        for name in ("python3", "python"):
            found = shutil.which(name)
            if found:
                candidates.append(found)

    seen = set()
    ordered = []
    for c in candidates:
        if c not in seen:
            seen.add(c)
            ordered.append(c)

    for c in ordered:
        if not _is_windowsapps_stub(c) and _python_actually_runs(c):
            return c
    # Nothing non-stub worked; fall back to the stub only if it genuinely
    # runs (better than nothing -- callers treat None as "skip banner").
    for c in ordered:
        if _python_actually_runs(c):
            return c
    return None


def _installed_plugin_root(home=None):
    """Read ~/.claude/plugins/installed_plugins.json for the forge plugin's
    installPath -- the productized plugin cache the shim will actually run
    against, not this dev checkout. The marketplace half of the key varies
    (forge@orns-forge post-rename, forge@forge-local pre-migration, any
    forge@<marketplace> for a public install), so resolve known names first,
    then fall back to any forge@ key."""
    home = Path(home) if home else Path.home()
    plugins_json = home / ".claude" / "plugins" / "installed_plugins.json"
    try:
        # utf-8-sig, not utf-8: PowerShell's default Out-File/Set-Content
        # writes UTF-8-with-BOM, and a bare "utf-8" read leaves the BOM in
        # the string, which makes json.loads raise (silently swallowed by
        # the except below, breaking plugin-root resolution).
        data = json.loads(plugins_json.read_text(encoding="utf-8-sig"))
        plugins = data.get("plugins", {})
        entries = None
        for key in ("forge@orns-forge", "forge@forge-local"):
            if plugins.get(key):
                entries = plugins[key]
                break
        if entries is None:
            entries = next(
                (v for k, v in sorted(plugins.items())
                 if k.startswith("forge@") and v),
                None,
            )
        if not entries:
            return None
        install_path = entries[0].get("installPath")
        return Path(install_path) if install_path else None
    except Exception:
        return None


def resolve_banner_py_path(home=None):
    """tools/banner.py from the INSTALLED plugin cache; falls back to the
    path next to this file for a dev-tree run (banner_install.py and
    banner.py are siblings in tools/ in both trees)."""
    root = _installed_plugin_root(home=home)
    if root is not None:
        candidate = root / "tools" / "banner.py"
        if candidate.is_file():
            return candidate
    dev_candidate = Path(__file__).resolve().parent / "banner.py"
    if dev_candidate.is_file():
        return dev_candidate
    return None


# ---------------------------------------------------------------------------
# Marker-block text transform -- pure, no I/O. Shared by PowerShell profiles
# and bash/zsh rc files.
# ---------------------------------------------------------------------------

def _marker_block_pattern(marker_start=MARKER_START, marker_end=MARKER_END):
    return re.compile(re.escape(marker_start) + r".*?" + re.escape(marker_end),
                       re.DOTALL)


def upsert_marker_block(existing_text, new_body, marker_start=MARKER_START,
                         marker_end=MARKER_END):
    """Insert or replace the marker-guarded block in existing_text.

    Detects a pre-existing block bounded by the same markers -- including a
    hand-rolled one a user installed by hand, since the hand fix used this
    exact marker text -- and replaces it in place ("upgraded"). If none
    exists, appends a new block ("installed"). Calling this twice with the
    same new_body is idempotent: the second call returns the input
    unchanged and reports "unchanged".

    Returns (new_text, action) where action is one of
    "installed" | "upgraded" | "unchanged".
    """
    existing_text = existing_text or ""
    new_block = f"{marker_start}\n{new_body.strip(chr(10))}\n{marker_end}"
    match = _marker_block_pattern(marker_start, marker_end).search(existing_text)
    if match:
        if match.group(0) == new_block:
            return existing_text, "unchanged"
        new_text = existing_text[:match.start()] + new_block + existing_text[match.end():]
        return new_text, "upgraded"

    prefix = existing_text
    if prefix and not prefix.endswith("\n"):
        prefix += "\n"
    if prefix and not prefix.endswith("\n\n"):
        prefix += "\n"
    new_text = prefix + new_block + "\n"
    return new_text, "installed"


def remove_marker_block(existing_text, marker_start=MARKER_START,
                         marker_end=MARKER_END):
    """Remove exactly the marker-guarded block (and the blank-line
    separation it introduced) -- nothing else in the file is touched.

    Returns (new_text, removed: bool). Idempotent: calling this again on
    text with no block present returns the input unchanged with removed=False.
    """
    if not existing_text:
        return existing_text or "", False
    pattern = re.compile(
        r"\n*" + re.escape(marker_start) + r".*?" + re.escape(marker_end) + r"\n?",
        re.DOTALL,
    )
    new_text, count = pattern.subn("", existing_text)
    return new_text, count > 0


def has_marker_block(existing_text, marker_start=MARKER_START, marker_end=MARKER_END):
    return bool(_marker_block_pattern(marker_start, marker_end).search(existing_text or ""))


# ---------------------------------------------------------------------------
# Shim body generators -- pure string builders, one per shell surface.
# ---------------------------------------------------------------------------

def _ps_quote(value):
    return "'" + str(value).replace("'", "''") + "'"


def _require_real_claude_path(claude_path):
    """Placeholder-proof guard (fg-a10904 3rd-incident hardening): a shim
    body generator must never bake in a claude CLI path that does not exist
    as a real file on disk. This is what a stale/hand-edited/TEST-FIXTURE
    placeholder path (e.g. the literal 'C:\\real\\claude.exe' that caused
    the 2026-07 real-machine incident) looks like -- a string that LOOKS
    like a path but resolves to nothing. None is fine (means "not resolved
    at install time", handled by each generator's own fallback branch);
    anything else must be Path(...).is_file() or this raises ValueError."""
    if claude_path is None:
        return
    if not Path(claude_path).is_file():
        raise ValueError(
            f"refusing to generate a shim pointing at {claude_path!r} -- "
            "that path does not exist as a real file. This is exactly the "
            "placeholder/broken-path shim class that caused the real-"
            "machine incident this guard exists to prevent."
        )


def build_powershell_body(claude_path, python_path, banner_py_path):
    """PowerShell `claude` function: invokes `banner.py --anim`, skips
    -p/--print, try/catch fails open to a plain launch if the banner step
    errors for any reason.

    fg-a10905: --anim is SELF-TIMED (a ~2.6s, 30-frame gleam sweep) -- the
    animation itself is the launch-visibility hold that fg-a10904's
    POST-BUILD FINDING established was needed (the Claude TUI wipes the
    console via an alternate screen buffer immediately on launch), so no
    separate Start-Sleep is needed alongside it any more.

    CRITICAL INVARIANT: python is invoked DIRECTLY here, never piped
    through `| Out-Host`. Piping captures stdout as objects and buffers it
    until the process exits, which defeats the animation's cursor-up +
    \\x1b[2K redraw loop (only the final frame would ever appear). `2>$null`
    alone (stderr-only redirection, no pipe) does not have this problem --
    stdout still streams straight to the console in real time.
    """
    _require_real_claude_path(claude_path)
    lines = ["function claude {"]
    lines.append("    if (($args -notcontains '-p') -and ($args -notcontains '--print')) {")
    lines.append("        try {")
    if python_path and banner_py_path:
        lines.append(
            f"            & {_ps_quote(python_path)} {_ps_quote(str(banner_py_path))} "
            "--anim 2>$null"
        )
        # bm-banner-takeover: silent auto-repatch check, opt-in gated (a
        # total no-op unless `/forge:banner install` has already run once --
        # see recheck_patch() in banner.py). Re-verifies/re-patches the CLI
        # bundle after a Claude Code update, every launch.
        lines.append(
            f"            & {_ps_quote(python_path)} {_ps_quote(str(banner_py_path))} "
            "--recheck-patch 2>$null"
        )
    else:
        lines.append("            # python/banner.py not resolved at install time; skipped.")
    lines.append("        } catch {}")
    lines.append("    }")
    if claude_path:
        lines.append(f"    & {_ps_quote(claude_path)} @args")
    else:
        lines.append("    & claude.exe @args  # claude CLI path not resolved at install time")
    lines.append("}")
    return "\n".join(lines)


def build_bash_body(claude_path, python_path, banner_py_path):
    """bash/zsh `claude` function equivalent to the PowerShell one.

    fg-a10905: invokes `banner.py --anim`, which is self-timed (~2.6s
    gleam sweep) -- the animation itself is the launch-visibility hold
    (the Claude TUI wipes the console on launch), so no separate sleep is
    needed any more. Lives inside the same -p/--print skip-guard as the
    banner (fg-a10904)."""
    _require_real_claude_path(claude_path)
    lines = ["claude() {"]
    lines.append("    __forge_skip_banner=0")
    lines.append('    for __forge_arg in "$@"; do')
    lines.append('        case "$__forge_arg" in')
    lines.append("            -p|--print) __forge_skip_banner=1 ;;")
    lines.append("        esac")
    lines.append("    done")
    lines.append('    if [ "$__forge_skip_banner" -eq 0 ]; then')
    if python_path and banner_py_path:
        lines.append(f'        "{python_path}" "{banner_py_path}" --anim 2>/dev/null || true')
        # bm-banner-takeover: silent auto-repatch check, opt-in gated (see
        # the PowerShell body above for the full rationale).
        lines.append(f'        "{python_path}" "{banner_py_path}" --recheck-patch 2>/dev/null || true')
    else:
        lines.append("        : # python/banner.py not resolved at install time; skipped.")
    lines.append("    fi")
    lines.append("    unset __forge_skip_banner __forge_arg")
    if claude_path:
        lines.append(f'    command "{claude_path}" "$@"')
    else:
        lines.append('    command claude "$@"')
    lines.append("}")
    return "\n".join(lines)


def build_claude_bat(claude_path, python_path, banner_py_path):
    """cmd.exe shim: skips -p/--print, fails silent (2>nul) if python or
    banner.py is missing, calls the real claude.exe with an absolute path
    resolved at install time (never hardcoded).

    fg-a10905: invokes `banner.py --anim`, self-timed (~2.6s gleam sweep)
    inside the SAME FORGE_SKIP_BANNER guard used for the banner call itself
    -- the animation is now the launch-visibility hold fg-a10904's
    POST-BUILD FINDING established was needed (the Claude TUI wipes the
    console via an alternate screen buffer on launch), so the separate
    `ping` hold that used to live here is gone. -p/--print skip the guard
    entirely, so they get neither the banner nor the hold."""
    _require_real_claude_path(claude_path)
    lines = ["@echo off", FORGE_BAT_TAG, "setlocal"]
    lines.append("set FORGE_SKIP_BANNER=0")
    lines.append("for %%A in (%*) do (")
    lines.append('    if /I "%%~A"=="-p" set FORGE_SKIP_BANNER=1')
    lines.append('    if /I "%%~A"=="--print" set FORGE_SKIP_BANNER=1')
    lines.append(")")
    lines.append('if "%FORGE_SKIP_BANNER%"=="0" (')
    if python_path and banner_py_path:
        lines.append(f'    "{python_path}" "{banner_py_path}" --anim 2>nul')
        # bm-banner-takeover: silent auto-repatch check, opt-in gated (see
        # the PowerShell body above for the full rationale).
        lines.append(f'    "{python_path}" "{banner_py_path}" --recheck-patch 2>nul')
    else:
        # F8 (verify-bounce finding): PowerShell/bash both emit an explicit
        # comment here when python/banner.py couldn't be resolved at
        # install time -- cmd.exe must match, not silently emit nothing.
        # REM is cmd's comment syntax (# is not).
        lines.append('    REM python/banner.py not resolved at install time; skipped.')
    lines.append(")")
    if claude_path:
        lines.append(f'"{claude_path}" %*')
    else:
        lines.append("claude.exe %*")
    lines.append("endlocal")
    return "\r\n".join(lines) + "\r\n"


def build_autorun_cmd(claude_bat_path):
    """The AutoRun target: defines the `claude` doskey macro. doskey macros
    only expand for an *interactive* cmd session, so `cmd /c ...` and
    scripts invoking `claude` stay clean without any extra guard."""
    lines = [
        "@echo off",
        FORGE_AUTORUN_TAG,
        f'doskey claude=call "{claude_bat_path}" $*',
    ]
    return "\r\n".join(lines) + "\r\n"


def build_autorun_invocation(autorun_cmd_path):
    return f'"{autorun_cmd_path}"'


# ---------------------------------------------------------------------------
# AutoRun chaining -- pure logic, no registry I/O, fully unit-testable.
# ---------------------------------------------------------------------------

def compute_new_autorun(existing_value, our_invocation):
    """Idempotent AutoRun chaining. existing_value is the current AutoRun
    string (None/"" if unset). If our_invocation already appears anywhere in
    existing_value, returns it unchanged (idempotent re-install). Otherwise
    chains "existing & ours"."""
    existing_value = existing_value or ""
    if not existing_value.strip():
        return our_invocation
    if our_invocation in existing_value:
        return existing_value
    return existing_value.rstrip() + " & " + our_invocation


def _normalize_autorun_segment(segment):
    """Normalize a single '&'-delimited AutoRun command segment for EQUALITY
    comparison: strip surrounding whitespace, strip one layer of
    surrounding double quotes if the whole (trimmed) segment is quoted, and
    lowercase (Windows path comparisons are case-insensitive). Used only to
    decide whether a segment IS our invocation -- never to rewrite the
    segment that gets kept, so an unrelated segment's original text/casing
    survives byte-identical."""
    segment = segment.strip()
    if len(segment) >= 2 and segment[0] == '"' and segment[-1] == '"':
        segment = segment[1:-1]
    return segment.lower()


def compute_autorun_after_uninstall(existing_value, our_invocation):
    """Unchain exactly our segment from AutoRun, leaving any other chained
    command byte-identical. Verify-bounce P1 fix: this used to do a raw
    str.replace() of our_invocation as a SUBSTRING anywhere in the value,
    which could corrupt unrelated content that merely embeds our path
    inside a longer command (e.g. `if exist "<our path>" echo keep` is not
    our segment, and must survive untouched). Splits the value into
    complete '&'-delimited segments, removes ONLY segments that are exactly
    (case-insensitively, quote-normalized) our invocation, and rejoins the
    survivors with ' & ' -- never a substring operation on the raw value.
    Returns the new value, or None if nothing is left (caller should delete
    the registry value entirely)."""
    if not existing_value:
        return None
    our_normalized = _normalize_autorun_segment(our_invocation)
    segments = existing_value.split("&")
    kept = [seg.strip() for seg in segments
            if _normalize_autorun_segment(seg) != our_normalized]
    result = " & ".join(seg for seg in kept if seg)
    return result or None


# ---------------------------------------------------------------------------
# Registry access -- the ONLY functions that touch HKCU. Import-guarded
# (winreg is None off Windows) and swappable via get_fn/set_fn params on the
# orchestration functions below, so tests never touch the real registry.
# ---------------------------------------------------------------------------

def get_autorun_value():
    if winreg is None:
        raise RuntimeError("winreg is not available on this platform")
    try:
        with winreg.OpenKey(winreg.HKEY_CURRENT_USER, REGISTRY_KEY_PATH) as key:
            value, _ = winreg.QueryValueEx(key, REGISTRY_VALUE_NAME)
            return value
    except FileNotFoundError:
        return None


def set_autorun_value(value):
    if winreg is None:
        raise RuntimeError("winreg is not available on this platform")
    if value is None:
        delete_autorun_value()
        return
    # CREATE the key if absent (New-Item equivalent) then set the value.
    with winreg.CreateKeyEx(winreg.HKEY_CURRENT_USER, REGISTRY_KEY_PATH) as key:
        winreg.SetValueEx(key, REGISTRY_VALUE_NAME, 0, winreg.REG_SZ, value)


def delete_autorun_value():
    if winreg is None:
        raise RuntimeError("winreg is not available on this platform")
    try:
        with winreg.OpenKey(winreg.HKEY_CURRENT_USER, REGISTRY_KEY_PATH, 0,
                             winreg.KEY_SET_VALUE) as key:
            winreg.DeleteValue(key, REGISTRY_VALUE_NAME)
    except FileNotFoundError:
        pass


_AUTORUN_LOCK_PATH = Path(tempfile.gettempdir()) / "forge-banner-autorun.lock"
_AUTORUN_LOCK_TIMEOUT = 5.0  # seconds
_AUTORUN_LOCK_POLL = 0.05  # seconds between retries
# Comfortably longer than any real install/uninstall run -- a lock file
# older than this was left behind by a process that crashed before reaching
# __exit__, not a live contender (fg-a11031).
_AUTORUN_LOCK_STALE_SECONDS = 30.0


class _AutorunLock:
    """Minimal cross-process lock guarding the AutoRun read-modify-write.

    Two concurrent `/forge:banner install`/`uninstall` invocations each do
    an unsynchronized get_fn() ... set_fn() -- without serialization one can
    clobber the other's change (TOCTOU). This is a plain lock FILE, not a
    real mutex: acquired via os.open with O_CREAT|O_EXCL (atomic
    create-if-absent, enforced by the OS across processes), retried briefly,
    released by deleting the file. Good enough for a rare, fast,
    human-triggered CLI operation -- no need for a full mutex library.

    A lock file whose mtime is older than `stale_seconds` is presumed
    abandoned by a crashed process (one that acquired it but never reached
    __exit__) and is reclaimed (deleted, then the create is retried)
    immediately rather than waited out over the full `timeout` -- otherwise
    every subsequent caller would wait out the fixed timeout and then
    proceed via the `return self` fallback with `self._fd` left None,
    running the unsynchronized critical section with no mutual exclusion at
    all (the exact TOCTOU race this lock exists to prevent).
    """

    def __init__(self, path=_AUTORUN_LOCK_PATH, timeout=_AUTORUN_LOCK_TIMEOUT,
                 stale_seconds=_AUTORUN_LOCK_STALE_SECONDS):
        self.path = Path(path)
        self.timeout = timeout
        self.stale_seconds = stale_seconds
        self._fd = None

    def _reclaim_if_stale(self):
        """If `self.path` exists and its mtime is older than
        `self.stale_seconds`, delete it (abandoned-lock reclaim) and return
        True so the caller retries the atomic create immediately. Returns
        False if the file is missing (already reclaimed by another
        contender), unreadable, or not yet stale."""
        try:
            mtime = self.path.stat().st_mtime
        except OSError:
            return False
        if time.time() - mtime < self.stale_seconds:
            return False
        try:
            self.path.unlink()
        except OSError:
            pass
        return True

    def __enter__(self):
        deadline = time.monotonic() + self.timeout
        while True:
            try:
                self._fd = os.open(str(self.path), os.O_CREAT | os.O_EXCL | os.O_WRONLY)
                return self
            except (FileExistsError, PermissionError):
                if self._reclaim_if_stale():
                    continue  # retry the create immediately, no sleep
                if time.monotonic() >= deadline:
                    # A live (non-stale) contender still holds it after the
                    # full timeout -- proceed rather than deadlock forever.
                    # The registry ops are still individually correct; this
                    # only stops serializing against the laggard.
                    return self
                time.sleep(_AUTORUN_LOCK_POLL)

    def __exit__(self, exc_type, exc, tb):
        if self._fd is not None:
            try:
                os.close(self._fd)
            except OSError:
                pass
        try:
            self.path.unlink()
        except OSError:
            pass
        return False


def install_autorun(autorun_cmd_path, get_fn=None, set_fn=None):
    """Install/adopt/chain the AutoRun macro. Returns (action, new_value)
    where action is "installed" | "chained" | "unchanged".

    get_fn/set_fn default to None rather than being bound directly to
    get_autorun_value/set_autorun_value as default PARAMETER values: a
    default parameter value is captured once, at function-definition time
    (module import), so a later `banner_install.get_autorun_value =
    <monkeypatch>` (e.g. the tools/conftest.py hermeticity guard) would
    never be seen by a caller relying on this default -- the resolution
    below is a plain module-global NAME lookup instead, performed fresh on
    every call, so a monkeypatch of the module attribute is honored."""
    get_fn = get_fn or get_autorun_value
    set_fn = set_fn or set_autorun_value
    our_invocation = build_autorun_invocation(autorun_cmd_path)
    with _AutorunLock():
        existing = get_fn()
        new_value = compute_new_autorun(existing, our_invocation)
        if new_value == (existing or ""):
            return "unchanged", existing
        set_fn(new_value)
        action = "installed" if not existing or not existing.strip() else "chained"
        return action, new_value


def uninstall_autorun(autorun_cmd_path, get_fn=None, set_fn=None):
    """Remove exactly our AutoRun segment, unchaining carefully. Returns
    (action, new_value) where action is "removed" | "unchained" | "absent".
    See install_autorun's docstring for why get_fn/set_fn default to None
    and are resolved via a module-global lookup rather than a captured
    default parameter value."""
    get_fn = get_fn or get_autorun_value
    set_fn = set_fn or set_autorun_value
    our_invocation = build_autorun_invocation(autorun_cmd_path)
    with _AutorunLock():
        existing = get_fn()
        if not existing:
            return "absent", existing
        new_value = compute_autorun_after_uninstall(existing, our_invocation)
        if new_value == existing:
            # Segment-based comparison found nothing to remove -- either
            # our invocation is genuinely absent, or it only appears
            # embedded inside an unrelated command (never a real segment
            # match, see compute_autorun_after_uninstall's own docstring).
            # Either way there is nothing to write: report "absent" and
            # skip the registry write entirely rather than round-tripping
            # an unchanged value through set_fn.
            return "absent", existing
        set_fn(new_value)
        return ("removed" if new_value is None else "unchained"), new_value


# ---------------------------------------------------------------------------
# File-target install/uninstall/status -- PowerShell profiles, bash/zsh rc.
# ---------------------------------------------------------------------------

def write_shim_file(path, content, newline=""):
    """Write a generated shim/AutoRun file (claude.bat, forge-autorun.cmd)
    to disk. The cmd.exe surface's equivalent of install_into_file below --
    kept as its own named function (rather than an inline path.write_text
    call in install_all) so the test hermeticity guard has a single,
    stable, mockable write boundary for this surface too."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline=newline)


def unlink_shim_file(path):
    """Delete a generated shim/AutoRun file (claude.bat, forge-autorun.cmd).
    restore_all()'s tagged-shim cleanup routes through this rather than
    calling Path.unlink() directly, mirroring write_shim_file above and
    banner.py's _unlink_path -- a single, stable, mockable delete boundary
    for the test hermeticity guard (3rd real-machine-incident hardening,
    P0 finding: every direct writer/deleter must be guardable, not just the
    ones the original guard happened to cover)."""
    try:
        Path(path).unlink()
    except FileNotFoundError:
        pass


def install_into_file(path, body, marker_start=MARKER_START, marker_end=MARKER_END):
    path = Path(path)
    # utf-8-sig: a BOM'd profile (Windows tooling default) must be stripped
    # on read, not preserved verbatim and rewritten unnormalized.
    existing = path.read_text(encoding="utf-8-sig") if path.is_file() else ""
    new_text, action = upsert_marker_block(existing, body, marker_start, marker_end)
    if action != "unchanged":
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(new_text, encoding="utf-8", newline="\n")
    return action


def uninstall_from_file(path, marker_start=MARKER_START, marker_end=MARKER_END):
    path = Path(path)
    if not path.is_file():
        return "absent"
    existing = path.read_text(encoding="utf-8-sig")
    new_text, removed = remove_marker_block(existing, marker_start, marker_end)
    if removed:
        path.write_text(new_text, encoding="utf-8", newline="\n")
        return "removed"
    return "absent"


def status_of_file(path, marker_start=MARKER_START, marker_end=MARKER_END):
    path = Path(path)
    if not path.is_file():
        return "no such file"
    text = path.read_text(encoding="utf-8-sig")
    return "installed" if has_marker_block(text, marker_start, marker_end) else "not installed"


# ---------------------------------------------------------------------------
# User-level orn-motd dedupe -- the plugin now ships its own welcome-area
# hook (hooks/hooks.json -> hooks/scripts/orn-motd.sh, registered
# unconditionally as part of the plugin), which does exactly what the
# 2026-07-18 hand-wired fix did: emit {"systemMessage": ...} from
# banner.py --hook. If a user-level SessionStart entry referencing
# 'orn-motd' (e.g. the hand fix at C:\Users\<user>\.claude\orn-motd.py,
# wired into ~/.claude/settings.json) survives alongside the now-active
# plugin hook, the örn art prints TWICE every session start. This detects
# and deregisters exactly that duplicate. It never deletes the underlying
# script file it didn't create -- only the settings.json wiring, so the
# change is restore-safe (a user who wants the old hand-wired hook back
# can always re-add the entry by hand; the file itself is left untouched).
# ---------------------------------------------------------------------------

def find_orn_motd_hook_indices(hooks_section):
    """Pure: given the 'hooks' dict from a settings.json-shaped document
    (lifecycle -> list of matcher-groups -> list of hook entries), return a
    list of (lifecycle, group_index, hook_index) for every hook entry whose
    command references 'orn-motd'."""
    hits = []
    for lifecycle, groups in (hooks_section or {}).items():
        for gi, group in enumerate(groups or []):
            for hi, hook in enumerate((group or {}).get("hooks", []) or []):
                if "orn-motd" in hook.get("command", ""):
                    hits.append((lifecycle, gi, hi))
    return hits


def remove_orn_motd_hooks(settings_data):
    """Pure, no I/O: returns (new_settings_data, removed_count).

    Removes exactly the hook entries whose command references 'orn-motd'
    from settings_data["hooks"], pruning now-empty matcher-groups and
    now-empty lifecycle lists, and leaves every other hook (any lifecycle,
    any tool) and every other top-level settings.json key untouched.
    Idempotent: a second call on the already-cleaned data returns it
    unchanged with removed_count 0.
    """
    data = dict(settings_data) if settings_data else {}
    hooks = data.get("hooks")
    if not hooks:
        return data, 0

    removed = 0
    new_hooks = {}
    for lifecycle, groups in hooks.items():
        new_groups = []
        for group in groups or []:
            hook_list = (group or {}).get("hooks", []) or []
            kept = [h for h in hook_list if "orn-motd" not in h.get("command", "")]
            removed += len(hook_list) - len(kept)
            if kept:
                new_group = dict(group)
                new_group["hooks"] = kept
                new_groups.append(new_group)
            # else: the whole matcher-group was only the orn-motd entry -- drop it.
        if new_groups:
            new_hooks[lifecycle] = new_groups
        # else: the whole lifecycle had nothing left -- drop the key.

    if removed == 0:
        return data, 0

    new_data = dict(data)
    if new_hooks:
        new_data["hooks"] = new_hooks
    else:
        new_data.pop("hooks", None)
    return new_data, removed


def dedupe_user_level_orn_motd(settings_path=None, read_fn=None, write_fn=None, home=None):
    """Detect + deregister a hand-wired user-level SessionStart hook
    referencing 'orn-motd' from ~/.claude/settings.json (or an injected
    path/read_fn/write_fn triple, for tests -- mirrors the get_fn/set_fn
    registry-stub pattern used for AutoRun below). Only ever touches the
    settings.json wiring; never deletes the script file it points at.
    Returns a human-readable report line, same style as install_all()/
    uninstall_all()'s other per-surface lines.
    """
    path = Path(settings_path) if settings_path else user_settings_path(home=home)

    if read_fn is not None:
        data = read_fn()
    else:
        if not path.is_file():
            return "user-level orn-motd hook: none found (no ~/.claude/settings.json)"
        try:
            # utf-8-sig: see _installed_plugin_root -- a BOM'd settings.json
            # (Windows tooling default) must not look "unreadable" here.
            data = json.loads(path.read_text(encoding="utf-8-sig"))
        except Exception:
            return "user-level orn-motd hook: settings.json unreadable, skipped"

    new_data, removed = remove_orn_motd_hooks(data)
    if removed == 0:
        return "user-level orn-motd hook: none found (nothing to dedupe)"

    if write_fn is not None:
        write_fn(new_data)
    else:
        try:
            write_shim_file(path, json.dumps(new_data, indent=2) + "\n")
        except Exception:
            return (f"user-level orn-motd hook: found {removed} but could not "
                     "remove (settings.json not writable) -- remove it by hand "
                     "to avoid the örn art printing twice")

    plural = "y" if removed == 1 else "ies"
    return (f"user-level orn-motd hook: removed {removed} duplicate entr{plural} "
            "from ~/.claude/settings.json (the plugin's own welcome-area hook "
            "now covers this; the script file itself was left in place)")


# ---------------------------------------------------------------------------
# Shell-surface detection
# ---------------------------------------------------------------------------

def detect_powershell_profiles():
    """Ask each installed PowerShell host for its own $PROFILE -- never
    guess the Documents\\WindowsPowerShell layout by hand (OneDrive
    redirection, PS7 vs 5.1, CDXML host differences all move $PROFILE)."""
    profiles = []
    for exe in ("powershell", "pwsh"):
        if shutil.which(exe) is None:
            continue
        try:
            result = subprocess.run(
                [exe, "-NoProfile", "-Command", "$PROFILE"],
                capture_output=True, text=True, timeout=15,
            )
            value = result.stdout.strip()
            if result.returncode == 0 and value:
                profiles.append((exe, Path(value)))
        except Exception:
            continue
    return profiles


def detect_shell_rc_files(home=None):
    home_path = Path(home) if home else Path.home()
    candidates = [("bash", home_path / ".bashrc"), ("zsh", home_path / ".zshrc")]
    return [(shell, path) for shell, path in candidates if path.is_file()]


def default_shim_dir(home=None):
    home_path = Path(home) if home else Path.home()
    return home_path / SHIM_DIRNAME


def user_settings_path(home=None):
    """~/.claude/settings.json (or under an injected home=) -- a lazy
    FUNCTION rather than a module-level Path.home() constant, so a home=
    parameter passed down from install_all/restore_all/dedupe_user_level_
    orn_motd can actually redirect it (the prior module-level
    USER_SETTINGS_PATH constant was resolved once at import time against
    the REAL Path.home() and could never honor a test's home= override --
    part of the 3rd real-machine-incident hardening)."""
    home_path = Path(home) if home else Path.home()
    return home_path / ".claude" / "settings.json"


# ---------------------------------------------------------------------------
# bm-banner-takeover: single-mode install. There is no separate splash-only
# path any more (owner delta 2026-07-22) -- `/forge:banner install` always
# means "patch the installed CLI's startup art + install the launcher shim
# that shows the Örn's Forge splash", gated on one explicit confirm. The
# confirm itself is procedural (commands/banner.md shows report_patch_plan()
# to the human and waits for a yes before ever passing confirmed=True) with
# a defense-in-depth mirror here: install_all(confirmed=False) -- the
# default -- performs NO writes at all and returns the same plan as a
# preview.
# ---------------------------------------------------------------------------

def _detect_claude_cli_version(claude_path):
    """F9: best-effort INFORMATIONAL version tag carried in the stamp. The
    stamp's authoritative key is the whole-file hash (banner.py's
    _classify_patch_plan compares patched_sha256, never version) -- this
    is metadata only, never load-bearing for correctness, and swallows
    every failure rather than blocking the install over a `--version`
    hiccup."""
    try:
        result = subprocess.run([claude_path, "--version"], capture_output=True,
                                 text=True, timeout=10)
        if result.returncode == 0:
            value = result.stdout.strip()
            return value or None
    except Exception:
        pass
    return None


def report_patch_plan(home=None, target_path=None):
    """Human-readable preview lines for the confirm step, built from
    banner.py's side-effect-free patch_report(). Never writes anything.

    F3: includes the exact target path AND its whole-file sha256. This is
    the confirm-to-write binding surface -- commands/banner.md captures
    both from this output and passes them back as --target/--expect-hash
    on the subsequent confirmed `install --yes` call, so apply_patch can
    refuse if either changed between preview and confirmation."""
    plan = banner_patch.patch_report(target_path=target_path, home=home)
    lines = [f"binary patch plan: {plan['status']}"]
    if plan.get("target"):
        lines.append(f"  target binary: {plan['target']}")
    if plan.get("target_sha256"):
        lines.append(f"  target sha256: {plan['target_sha256']}")
    if plan.get("count") is not None:
        lines.append(f"  escapes found: {plan['count']}"
                      + (f" (form: {plan['form']})" if plan.get("form") else ""))
    if plan.get("journal_path"):
        lines.append(f"  offsets journal would be written to: {plan['journal_path']}")
    if plan.get("stamp_path"):
        lines.append(f"  stamp would be written to: {plan['stamp_path']}")
    lines.append(f"  {plan['message']}")
    lines.append(f"  {banner_patch.DISCLOSURE}")
    return lines, plan


# ---------------------------------------------------------------------------
# Legacy-artifact detection (3rd real-machine-incident hardening).
#
# GROUND TRUTH: a real machine was found carrying a broken claude.bat (the
# literal TEST-FIXTURE placeholder path 'C:\real\claude.exe' baked into its
# target line) plus a forge-autorun.cmd wiring it into the HKCU AutoRun
# doskey macro -- doskey beats PATH for an interactive cmd.exe session, so
# this silently hijacked and broke the `claude` command in every CMD
# window, while `where claude` kept reporting the correct, working install
# because PATH resolution itself was never touched. These pure extraction
# helpers + scan_legacy_artifacts() detect exactly that shape so
# `/forge:banner status` can report it and `/forge:banner install` can
# refuse to layer a fresh install on top of it (see the preflight check in
# install_all below).
# ---------------------------------------------------------------------------

_BAT_TARGET_RE = re.compile(r'^"([^"]+)" %\*\s*$', re.MULTILINE)
_AUTORUN_TARGET_RE = re.compile(r'doskey claude=call "([^"]+)" \$\*')


def _extract_bat_target(text):
    """Pure: pull the claude CLI path a generated claude.bat launches, out
    of its own text -- the line build_claude_bat() emits as `"<path>" %*`.
    Returns None if the shape isn't found (not one of ours, or corrupted)."""
    match = _BAT_TARGET_RE.search(text or "")
    return match.group(1) if match else None


def _extract_autorun_target(text):
    """Pure: pull the claude.bat path a generated forge-autorun.cmd's
    doskey macro points at, out of its own text. Returns None if the shape
    isn't found."""
    match = _AUTORUN_TARGET_RE.search(text or "")
    return match.group(1) if match else None


def _is_ours_by_location(referenced_path, shim_dir):
    """Verify-bounce P1 fix support: when an AutoRun-referenced path
    doesn't exist on disk any more, we can't read a tag out of it to
    confirm it's forge-authored -- so a finding about it is only GATING
    (refuses install) when it's unambiguously ours BY LOCATION: its
    basename is our AutoRun-cmd filename, or it lives directly inside our
    own shim directory. Anything else (some unrelated program's AutoRun
    entry referencing some other missing file) is real, but not ours to
    gate an install on or promise restore will clear."""
    try:
        candidate = Path(referenced_path)
    except (TypeError, ValueError):
        return False
    if candidate.name.lower() == AUTORUN_CMD_NAME.lower():
        return True
    try:
        return candidate.parent.resolve() == shim_dir.resolve()
    except OSError:
        return candidate.parent == shim_dir


def scan_legacy_artifacts(home=None, get_autorun_fn=None):
    """Report-only scan for BROKEN legacy banner-shim artifacts left behind
    by an unclean prior install/uninstall -- never writes or deletes
    anything itself (see install_all's preflight refusal and restore_all's
    existing unconditional tagged-file removal for the actions taken on
    what this finds). Returns a list of finding dicts:
    {"message": str, "gating": bool}, empty when nothing was found.

    "gating" is True only for a finding this plugin can unambiguously
    attribute to itself (a shim/AutoRun-cmd file carrying our own tag, or
    an AutoRun-referenced path that is ours by location -- see
    _is_ours_by_location) -- install_all's preflight refuses ONLY on
    gating findings. A non-gating ("informational") finding -- e.g. some
    OTHER program's AutoRun entry referencing an unrelated missing file --
    is still reported (status_all surfaces every finding) but never blocks
    an install, and restore_all cannot and does not promise to clear it
    (verify-bounce P1 fix: the scan previously flagged, and install
    refused on, ANY missing quoted AutoRun path regardless of whether it
    had anything to do with forge at all).

    Every filesystem/registry read here is wrapped defensively: a shim
    that isn't ours (no FORGE_BAT_TAG/FORGE_AUTORUN_TAG), an unreadable
    file, or a blocked/unavailable registry read is treated as "nothing to
    report" rather than an error -- this is a best-effort report-only scan,
    never a hard failure path."""
    findings = []

    shim_dir = default_shim_dir(home=home)
    claude_bat = shim_dir / CLAUDE_BAT_NAME
    autorun_cmd = shim_dir / AUTORUN_CMD_NAME

    try:
        if claude_bat.is_file():
            text = claude_bat.read_text(encoding="utf-8", errors="ignore")
            if FORGE_BAT_TAG in text:
                target = _extract_bat_target(text)
                if target and not Path(target).is_file():
                    findings.append({
                        "gating": True,
                        "message": (
                            f"broken legacy shim: {claude_bat} targets a "
                            f"claude CLI path that no longer exists "
                            f"({target}) -- `claude` in cmd.exe will fail "
                            "while `where claude` may still look correct, "
                            "because doskey beats PATH."
                        ),
                    })
    except OSError:
        pass

    try:
        if autorun_cmd.is_file():
            text = autorun_cmd.read_text(encoding="utf-8", errors="ignore")
            if FORGE_AUTORUN_TAG in text:
                bat_target = _extract_autorun_target(text)
                if bat_target and not Path(bat_target).is_file():
                    findings.append({
                        "gating": True,
                        "message": (
                            f"broken legacy artifact: {autorun_cmd} "
                            f"references a claude.bat that no longer "
                            f"exists ({bat_target})."
                        ),
                    })
    except OSError:
        pass

    # READ-ONLY registry query, guarded: never writes, and any failure
    # (winreg unavailable, key missing, blocked by the test hermeticity
    # guard) is swallowed -- this scan degrades to "nothing to report"
    # rather than raising, same as every other guarded surface above.
    if os.name == "nt" and winreg is not None:
        get_fn = get_autorun_fn or get_autorun_value
        try:
            existing = get_fn()
        except Exception:
            existing = None
        if existing:
            for referenced_path in re.findall(r'"([^"]+)"', existing):
                if referenced_path and not Path(referenced_path).is_file():
                    gating = _is_ours_by_location(referenced_path, shim_dir)
                    findings.append({
                        "gating": gating,
                        "message": (
                            f"{'broken AutoRun entry' if gating else 'AutoRun entry (not ours)'}: "
                            f"HKCU\\{REGISTRY_KEY_PATH} AutoRun references "
                            f"a file that no longer exists "
                            f"({referenced_path})."
                        ),
                    })

    return findings


# ---------------------------------------------------------------------------
# Orchestration -- install / restore / status across every surface.
# ---------------------------------------------------------------------------

def install_all(confirmed=False, home=None, target=None, expect_hash=None, force=False):
    """Single-mode install.

    F4 -- no patch-only partials: BOTH plans (can the launcher shim even
    be installed? what would the binary patch do?) are effectively
    resolved before any write happens, and if the launcher can't proceed
    at all (no `claude` CLI resolvable on PATH), the ENTIRE install is
    refused -- nothing is written, not even a binary patch that might
    otherwise have been resolvable via the native-install-root fallback a
    PATH-only shim search doesn't see. Write order is shims FIRST, patch
    LAST: if any individual shim surface fails outright, the patch step
    is skipped entirely and the partial-shim state is reported honestly,
    rather than leaving a patched binary behind a broken shim install.

    F3 -- confirm bound to write: target/expect_hash (captured by the
    caller from a PRIOR report_patch_plan() preview) are forwarded
    straight through to apply_patch, which refuses if the resolved target
    or its current hash differs from what was actually confirmed.

    confirmed=False (the default) performs NO writes at all -- it only
    returns the same report lines a real install would produce, for the
    confirm step to show the human first. Pass confirmed=True only after
    that confirm succeeds."""
    if not confirmed:
        plan_lines, _ = report_patch_plan(home=home, target_path=target)
        return (["DRY RUN -- nothing installed or patched. Re-run confirmed "
                  "to actually apply this."] + plan_lines)

    report = []

    # --- Phase 1: resolve everything needed for BOTH plans -- no writes yet.
    claude_path = resolve_claude_cli_path()
    python_path = resolve_python_interpreter()
    banner_py_path = resolve_banner_py_path()

    if claude_path is None:
        return ["claude CLI not found on PATH -- refusing the ENTIRE "
                "install (patch-only partial installs are not allowed); "
                "nothing was written, including no binary patch even "
                "though one might otherwise have been resolvable via the "
                "native-install-root fallback."]

    # Placeholder-proof guard (3rd real-machine incident hardening): a
    # resolved claude_path that does not exist as a real file (a stale
    # PATH entry, a broken shim, a hand-edited placeholder) must refuse the
    # whole install exactly like claude_path is None above -- proceeding
    # would bake the broken path into every generated shim.
    if not Path(claude_path).is_file():
        return [f"claude CLI resolved to {claude_path!r} on PATH, but that "
                "path does not exist as a real file -- refusing the ENTIRE "
                "install (placeholder/broken-path guard); nothing was "
                "written. Fix or remove whatever put that path on PATH "
                "(a stale shim, a hand-edited launcher) and re-run install."]

    # Legacy-artifact preflight (report-only scan reused as a gate here,
    # but ONLY for findings this plugin can unambiguously attribute to
    # itself -- see scan_legacy_artifacts's "gating" docstring): a broken
    # legacy shim/AutoRun entry from a prior, unclean install of OURS must
    # be cleared with restore before a fresh install writes on top of it --
    # otherwise the new install can leave two conflicting `claude` shims
    # active at once (the exact doskey-beats-PATH incident shape). A
    # non-gating finding (some unrelated program's own broken AutoRun
    # entry) is real but not ours to refuse an install over, or to promise
    # restore will clear -- it's surfaced by status_all instead.
    gating_findings = [f["message"] for f in scan_legacy_artifacts(home=home)
                        if f["gating"]]
    if gating_findings:
        return (["Refusing install -- broken legacy banner-shim artifacts "
                  "were found on this machine. Run `/forge:banner --restore` "
                  "first to clear them, then re-run install:"]
                + [f"  - {finding}" for finding in gating_findings])

    # --- Phase 2: write the launcher shim FIRST, across every surface.
    # Every surface below is wrapped in its own try/except: a failure on ONE
    # surface (e.g. PermissionError on a locked PowerShell $PROFILE) must
    # not crash the whole multi-surface operation and leave every later
    # surface untried -- record a "FAILED -- <error>" report line and keep
    # going, same style as dedupe_user_level_orn_motd()'s own failure lines.
    ps_body = build_powershell_body(claude_path, python_path, banner_py_path)
    ps_profiles = detect_powershell_profiles()
    for shell, profile_path in ps_profiles:
        try:
            action = install_into_file(profile_path, ps_body)
            report.append(f"{shell} profile ({profile_path}): {action}")
        except Exception as exc:
            report.append(f"{shell} profile ({profile_path}): FAILED -- {exc}")
    if not ps_profiles:
        report.append("no PowerShell host found on PATH -- skipped.")

    bash_body = build_bash_body(claude_path, python_path, banner_py_path)
    rc_files = detect_shell_rc_files(home=home)
    for shell, rc_path in rc_files:
        try:
            action = install_into_file(rc_path, bash_body)
            report.append(f"{shell} rc ({rc_path}): {action}")
        except Exception as exc:
            report.append(f"{shell} rc ({rc_path}): FAILED -- {exc}")
    if not rc_files:
        report.append("no ~/.bashrc or ~/.zshrc found -- skipped (nothing to adopt).")

    if os.name == "nt":
        shim_dir = default_shim_dir(home=home)
        claude_bat = shim_dir / CLAUDE_BAT_NAME
        autorun_cmd = shim_dir / AUTORUN_CMD_NAME
        shim_written = False
        try:
            write_shim_file(claude_bat, build_claude_bat(claude_path, python_path, banner_py_path))
            write_shim_file(autorun_cmd, build_autorun_cmd(claude_bat))
            report.append(f"cmd shim written: {claude_bat}")
            shim_written = True
        except Exception as exc:
            report.append(f"cmd shim ({claude_bat}): FAILED -- {exc}")

        if winreg is not None:
            if shim_written:
                try:
                    action, _ = install_autorun(autorun_cmd)
                    report.append(f"cmd AutoRun (HKCU\\{REGISTRY_KEY_PATH}): {action}")
                except Exception as exc:
                    report.append(f"cmd AutoRun (HKCU\\{REGISTRY_KEY_PATH}): FAILED -- {exc}")
            else:
                report.append(f"cmd AutoRun (HKCU\\{REGISTRY_KEY_PATH}): "
                               "skipped, shim write failed")
        else:
            report.append("cmd AutoRun: winreg unavailable, skipped.")
    else:
        report.append("cmd.exe shim: not on Windows, skipped.")

    report.append('Note: Win+R "claude" (Run dialog) bypasses every shim above '
                   "-- out of scope, not wrapped.")

    # The plugin's own welcome-area hook (hooks/scripts/orn-motd.sh) is
    # shipped and active as soon as the plugin is installed -- independent
    # of this launcher-shim install. If a hand-wired user-level duplicate
    # is still registered, it would double-print the örn art every session.
    try:
        report.append(dedupe_user_level_orn_motd(home=home))
    except Exception as exc:
        report.append(f"user-level orn-motd hook: FAILED -- {exc}")

    # --- Phase 3: patch LAST (F4), and only if every shim surface above
    # actually succeeded -- a FAILED line anywhere means an incomplete
    # shim install, and this refuses to layer a binary patch on top of
    # that rather than reporting a false "fully installed" state.
    shim_failed = any(" FAILED -- " in line for line in report)
    if shim_failed:
        report.append("binary patch: skipped -- one or more shim surfaces "
                       "above FAILED; reporting the partial-shim state "
                       "honestly rather than patching on top of an "
                       "incomplete install. Fix the failure(s) above and "
                       "re-run install to complete the patch.")
    else:
        cli_version = _detect_claude_cli_version(claude_path)
        patch_result = banner_patch.apply_patch(
            target_path=target, home=home, cli_version=cli_version,
            force=force, expect_target=target, expect_hash=expect_hash)
        report.append(f"binary patch ({patch_result.get('target')}): "
                       f"{patch_result['status']} -- {patch_result['message']}")

    return report


def restore_all(home=None):
    """`/forge:banner --restore`: byte-exactly restores the patched binary
    AND removes every shim/wrapper/AutoRun entry this plugin installed,
    AND removes the takeover stamp. Always available, no confirm needed --
    it only ever reverts state this plugin itself created."""
    report = []
    patch_result = banner_patch.restore_patch(home=home)
    report.append(f"binary restore ({patch_result.get('target')}): "
                   f"{patch_result['status']} -- {patch_result['message']}")

    for shell, profile_path in detect_powershell_profiles():
        try:
            action = uninstall_from_file(profile_path)
            report.append(f"{shell} profile ({profile_path}): {action}")
        except Exception as exc:
            report.append(f"{shell} profile ({profile_path}): FAILED -- {exc}")

    for shell, rc_path in detect_shell_rc_files(home=home):
        try:
            action = uninstall_from_file(rc_path)
            report.append(f"{shell} rc ({rc_path}): {action}")
        except Exception as exc:
            report.append(f"{shell} rc ({rc_path}): FAILED -- {exc}")

    if os.name == "nt":
        shim_dir = default_shim_dir(home=home)
        claude_bat = shim_dir / CLAUDE_BAT_NAME
        autorun_cmd = shim_dir / AUTORUN_CMD_NAME
        if winreg is not None:
            try:
                action, new_value = uninstall_autorun(autorun_cmd)
                report.append(f"cmd AutoRun (HKCU\\{REGISTRY_KEY_PATH}): {action}")
                # "absent" covers two different situations: genuinely never
                # installed (new_value falsy) vs. the registry value holds
                # something that doesn't match our invocation at all (a
                # mismatch). Silently deleting the shim files in the latter
                # case would leave a dangling AutoRun entry pointing at a
                # now-missing file -- still clean up our own artifacts
                # below, but surface an explicit warning so the user knows
                # to check the registry by hand.
                if action == "absent" and new_value:
                    report.append(
                        f"WARNING: cmd AutoRun (HKCU\\{REGISTRY_KEY_PATH}) still "
                        f"holds a value that does not reference the forge shim "
                        f"({new_value!r}) -- check it by hand; shim files are "
                        "still being removed below."
                    )
            except Exception as exc:
                report.append(f"cmd AutoRun (HKCU\\{REGISTRY_KEY_PATH}): FAILED -- {exc}")
        for shim_file, tag in ((claude_bat, FORGE_BAT_TAG), (autorun_cmd, FORGE_AUTORUN_TAG)):
            try:
                if shim_file.is_file():
                    try:
                        text = shim_file.read_text(encoding="utf-8", errors="ignore")
                    except OSError:
                        text = ""
                    if tag in text:
                        unlink_shim_file(shim_file)
                        report.append(f"cmd shim removed: {shim_file}")
                    else:
                        report.append(f"cmd shim ({shim_file}): not forge-authored, left alone")
                else:
                    report.append(f"cmd shim ({shim_file}): absent")
            except Exception as exc:
                report.append(f"cmd shim ({shim_file}): FAILED -- {exc}")

    # Uninstalling the launcher shim does not affect the plugin's own
    # welcome-area hook (hooks/scripts/orn-motd.sh) -- that stays wired via
    # hooks.json regardless. A stale user-level duplicate would still
    # double-print the örn art, so dedupe here too.
    try:
        report.append(dedupe_user_level_orn_motd(home=home))
    except Exception as exc:
        report.append(f"user-level orn-motd hook: FAILED -- {exc}")
    return report


# uninstall_all is the pre-takeover name; kept as an alias since it is the
# exact same operation now that restore always includes it (nothing to
# migrate callers off of -- both names do the full restore).
uninstall_all = restore_all


def status_all(home=None):
    report = []
    patch_stamp = banner_patch._read_stamp(banner_patch._patch_stamp_path(home))
    if patch_stamp:
        report.append(f"binary patch (target: {patch_stamp.get('target')}): "
                       f"installed (stamp: {banner_patch._patch_stamp_path(home)})")
    else:
        report.append("binary patch: not installed (no stamp found)")
    for shell, profile_path in detect_powershell_profiles():
        report.append(f"{shell} profile ({profile_path}): {status_of_file(profile_path)}")
    for shell, rc_path in detect_shell_rc_files(home=home):
        report.append(f"{shell} rc ({rc_path}): {status_of_file(rc_path)}")
    if os.name == "nt":
        shim_dir = default_shim_dir(home=home)
        claude_bat = shim_dir / CLAUDE_BAT_NAME
        autorun_cmd = shim_dir / AUTORUN_CMD_NAME
        report.append(f"cmd shim ({claude_bat}): "
                       f"{'present' if claude_bat.is_file() else 'absent'}")
        if winreg is not None:
            existing = get_autorun_value()
            our_invocation = build_autorun_invocation(autorun_cmd)
            if existing and our_invocation in existing:
                state = "installed"
            elif existing:
                state = f"AutoRun set to something else: {existing!r}"
            else:
                state = "not installed"
            report.append(f"cmd AutoRun (HKCU\\{REGISTRY_KEY_PATH}): {state}")
        else:
            report.append("cmd AutoRun: winreg unavailable, cannot check.")

    # Legacy-artifact scan (report-only): a broken shim/AutoRun entry left
    # behind by an unclean prior install/uninstall (e.g. the doskey-beats-
    # PATH incident -- see commands/banner.md) manifests as `claude` failing
    # in cmd.exe while `where claude` still looks correct. Surfaced here so
    # `/forge:banner status` can catch it without the user having to debug
    # a launch failure blind.
    legacy_findings = scan_legacy_artifacts(home=home)
    if legacy_findings:
        for finding in legacy_findings:
            label = "legacy scan" if finding["gating"] else "legacy scan (informational, not ours)"
            report.append(f"{label}: {finding['message']}")
    else:
        report.append("legacy scan: no broken legacy banner-shim artifacts found")
    return report


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

_NO_TARGET_SENTINEL = "none"  # case-insensitive; means "the preview found no patchable target"


def main(argv=None):
    parser = argparse.ArgumentParser(
        prog="banner_install.py",
        description=("Install (binary patch + launcher shim, single mode) / "
                      "restore / status the Forge örn banner takeover."),
    )
    parser.add_argument("action",
                         choices=["install", "restore", "uninstall", "status"])
    parser.add_argument(
        "--yes", action="store_true",
        help=("Actually perform the install (binary patch + shims). Without "
              "this flag, 'install' only PREVIEWS what would happen -- the "
              "confirm-before-patch step commands/banner.md relies on."),
    )
    parser.add_argument(
        "--target",
        help=(f"F3 confirm-to-write binding: the exact target path captured "
              f"from a prior `install` (no --yes) preview. REQUIRED with "
              f"--yes -- pass the literal value '{_NO_TARGET_SENTINEL}' if "
              f"the preview reported no patchable target at all."),
    )
    parser.add_argument(
        "--expect-hash",
        help=("F3 confirm-to-write binding: the target's whole-file sha256 "
              f"captured from that same preview. REQUIRED with --yes -- "
              f"pass '{_NO_TARGET_SENTINEL}' alongside --target "
              f"'{_NO_TARGET_SENTINEL}' when there was no target."),
    )
    parser.add_argument(
        "--force", action="store_true",
        help=("Patch even a 'low-count' plan (see banner.py's "
              "_LOW_COUNT_THRESHOLD) -- only use this after deliberately "
              "reviewing the low-count warning; never passed automatically."),
    )
    args = parser.parse_args(argv)

    if args.action == "install":
        if args.yes and (not args.target or not args.expect_hash):
            lines = [
                "Refusing: install --yes requires --target and --expect-hash "
                "captured from a prior `install` (no --yes) preview run -- "
                "this binds the confirmed plan to the actual write (F3). Run "
                "`install` first, read the reported target/sha256 (or note "
                f"there was none), then re-run with --yes --target <path> "
                f"--expect-hash <hash> (or both '{_NO_TARGET_SENTINEL}' if "
                "the preview found no patchable target).",
            ]
        elif args.yes:
            target = None if args.target.lower() == _NO_TARGET_SENTINEL else args.target
            expect_hash = None if args.expect_hash.lower() == _NO_TARGET_SENTINEL else args.expect_hash
            lines = install_all(confirmed=True, target=target,
                                 expect_hash=expect_hash, force=args.force)
        else:
            lines = install_all(confirmed=False)
    elif args.action in ("restore", "uninstall"):
        lines = restore_all()
    else:
        lines = status_all()

    for line in lines:
        print(line)
    return 0


if __name__ == "__main__":
    sys.exit(main())
