#!/usr/bin/env python3
"""Forge banner launcher installer/uninstaller (fg-a10904).

A Claude Code SessionStart hook cannot paint the user's terminal: its
stdout becomes model context, not terminal output. That is why
hooks/hooks.json no longer wires hooks/scripts/banner.sh into SessionStart
(root cause discovered 2026-07-18: the örn banner rendered into the model's
context every session and the user never saw a single pixel of it). The only
way to actually show the banner in a terminal is an OPT-IN shell launcher
shim that intercepts the `claude` command, prints the banner to the real
terminal, and then hands off to the real CLI. This module installs,
upgrades, uninstalls, and reports the status of that shim across every shell
surface Windows exposes. Invoked by commands/banner.md (`/forge:banner`).

Shell surfaces covered, per the live-debug ground truth captured in
.forge/queue/tasks/fg-a10904-banner-launcher.md (2026-07-18, user's machine):

  - PowerShell ($PROFILE, both `powershell` and `pwsh` if installed): a
    marker-guarded `claude` function that invokes `banner.py --anim`
    (fg-a10905) DIRECTLY -- never piped through `| Out-Host`, which would
    buffer output and defeat the animation's cursor-up redraws -- skips
    -p/--print, try/catch fail-open to a plain launch. Detects and upgrades
    a hand-rolled block using the same markers (the 2026-07-18 hand fix
    used this exact marker text).
  - cmd.exe: a shim dir (claude.bat) is NOT sufficient on its own -- if the
    real claude.exe's directory sits on the SYSTEM PATH it shadows a
    user-PATH shim, because cmd searches the system PATH first. The working
    mechanism is a doskey macro loaded via the HKCU AutoRun registry value
    (doskey only expands interactively, so `cmd /c` and scripts are
    unaffected "for free"). AutoRun is created if absent and chained
    ("existing & ours") if something else already occupies it.
  - bash/zsh (~/.bashrc, ~/.zshrc), when present: an equivalent function.

Out of scope, documented rather than handled: Win+R "claude" (the Run
dialog) launches claude.exe directly and bypasses every shim below -- there
is no interception point for that path.

Stdlib only, per the project constitution. Every shell-surface transform is
a pure, independently testable unit (marker-block upsert/remove, AutoRun
chaining) that takes plain strings and does no I/O; the thin wrappers around
them are the only things that touch the real filesystem or registry, and
registry access is behind get_autorun_value/set_autorun_value so tests can
stub it out without ever touching HKCU.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

try:
    import winreg  # type: ignore[import-not-found]
except ImportError:  # pragma: no cover - exercised only on non-Windows
    winreg = None


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

MARKER_START = "# >>> forge örn banner >>>"
MARKER_END = "# <<< forge örn banner <<<"

SHIM_DIRNAME = os.path.join(".local", "shims")
CLAUDE_BAT_NAME = "claude.bat"
AUTORUN_CMD_NAME = "forge-autorun.cmd"

REGISTRY_KEY_PATH = r"Software\Microsoft\Command Processor"
REGISTRY_VALUE_NAME = "AutoRun"

# Identifying tags written into the generated shim files, so uninstall only
# ever deletes files it recognizes as its own (never an unrelated user file
# that happens to share the name).
FORGE_BAT_TAG = ("REM forge-banner-shim (fg-a10904) -- regenerated by "
                  "/forge:banner install, safe to delete")
FORGE_AUTORUN_TAG = ("REM forge-banner-autorun (fg-a10904) -- regenerated by "
                      "/forge:banner install, safe to delete")


# ---------------------------------------------------------------------------
# Resolution: claude CLI, python interpreter, banner.py -- all resolved at
# install time, never hardcoded (machines differ: npm prefix, nvm, a
# WindowsApps app-execution-alias stub shadowing the real Python on PATH).
# ---------------------------------------------------------------------------

def resolve_claude_cli_path():
    """Absolute path to the real `claude` CLI, or None if not found."""
    if os.name == "nt":
        try:
            result = subprocess.run(["where", "claude"], capture_output=True,
                                     text=True, timeout=10)
            if result.returncode == 0:
                for line in result.stdout.splitlines():
                    line = line.strip()
                    if line:
                        return line
        except Exception:
            pass
    return shutil.which("claude")


def _python_actually_runs(path):
    try:
        result = subprocess.run([path, "--version"], capture_output=True,
                                 text=True, timeout=10)
        return result.returncode == 0
    except Exception:
        return False


def _is_windowsapps_stub(path):
    return "WindowsApps" in str(path)


def resolve_python_interpreter():
    """Absolute path to a working CPython interpreter, preferring a real
    install over the Windows Store app-execution-alias stub -- a bare
    python.exe under .../WindowsApps/ that can precede the real interpreter
    on PATH and, invoked directly, opens the Store rather than running
    (ground truth item 3). Verified with --version, never assumed."""
    candidates = []
    if os.name == "nt":
        try:
            result = subprocess.run(["where", "python"], capture_output=True,
                                     text=True, timeout=10)
            if result.returncode == 0:
                candidates.extend(
                    line.strip() for line in result.stdout.splitlines()
                    if line.strip()
                )
        except Exception:
            pass
    else:
        for name in ("python3", "python"):
            found = shutil.which(name)
            if found:
                candidates.append(found)

    seen = set()
    ordered = []
    for c in candidates:
        if c not in seen:
            seen.add(c)
            ordered.append(c)

    for c in ordered:
        if not _is_windowsapps_stub(c) and _python_actually_runs(c):
            return c
    # Nothing non-stub worked; fall back to the stub only if it genuinely
    # runs (better than nothing -- callers treat None as "skip banner").
    for c in ordered:
        if _python_actually_runs(c):
            return c
    return None


def _installed_plugin_root(home=None):
    """Read ~/.claude/plugins/installed_plugins.json for the forge plugin's
    installPath -- the productized plugin cache the shim will actually run
    against, not this dev checkout. The marketplace half of the key varies
    (forge@orns-forge post-rename, forge@forge-local pre-migration, any
    forge@<marketplace> for a public install), so resolve known names first,
    then fall back to any forge@ key."""
    home = Path(home) if home else Path.home()
    plugins_json = home / ".claude" / "plugins" / "installed_plugins.json"
    try:
        data = json.loads(plugins_json.read_text(encoding="utf-8"))
        plugins = data.get("plugins", {})
        entries = None
        for key in ("forge@orns-forge", "forge@forge-local"):
            if plugins.get(key):
                entries = plugins[key]
                break
        if entries is None:
            entries = next(
                (v for k, v in sorted(plugins.items())
                 if k.startswith("forge@") and v),
                None,
            )
        if not entries:
            return None
        install_path = entries[0].get("installPath")
        return Path(install_path) if install_path else None
    except Exception:
        return None


def resolve_banner_py_path(home=None):
    """tools/banner.py from the INSTALLED plugin cache; falls back to the
    path next to this file for a dev-tree run (banner_install.py and
    banner.py are siblings in tools/ in both trees)."""
    root = _installed_plugin_root(home=home)
    if root is not None:
        candidate = root / "tools" / "banner.py"
        if candidate.is_file():
            return candidate
    dev_candidate = Path(__file__).resolve().parent / "banner.py"
    if dev_candidate.is_file():
        return dev_candidate
    return None


# ---------------------------------------------------------------------------
# Marker-block text transform -- pure, no I/O. Shared by PowerShell profiles
# and bash/zsh rc files.
# ---------------------------------------------------------------------------

def _marker_block_pattern(marker_start=MARKER_START, marker_end=MARKER_END):
    return re.compile(re.escape(marker_start) + r".*?" + re.escape(marker_end),
                       re.DOTALL)


def upsert_marker_block(existing_text, new_body, marker_start=MARKER_START,
                         marker_end=MARKER_END):
    """Insert or replace the marker-guarded block in existing_text.

    Detects a pre-existing block bounded by the same markers -- including a
    hand-rolled one a user installed by hand, since the hand fix used this
    exact marker text -- and replaces it in place ("upgraded"). If none
    exists, appends a new block ("installed"). Calling this twice with the
    same new_body is idempotent: the second call returns the input
    unchanged and reports "unchanged".

    Returns (new_text, action) where action is one of
    "installed" | "upgraded" | "unchanged".
    """
    existing_text = existing_text or ""
    new_block = f"{marker_start}\n{new_body.strip(chr(10))}\n{marker_end}"
    match = _marker_block_pattern(marker_start, marker_end).search(existing_text)
    if match:
        if match.group(0) == new_block:
            return existing_text, "unchanged"
        new_text = existing_text[:match.start()] + new_block + existing_text[match.end():]
        return new_text, "upgraded"

    prefix = existing_text
    if prefix and not prefix.endswith("\n"):
        prefix += "\n"
    if prefix and not prefix.endswith("\n\n"):
        prefix += "\n"
    new_text = prefix + new_block + "\n"
    return new_text, "installed"


def remove_marker_block(existing_text, marker_start=MARKER_START,
                         marker_end=MARKER_END):
    """Remove exactly the marker-guarded block (and the blank-line
    separation it introduced) -- nothing else in the file is touched.

    Returns (new_text, removed: bool). Idempotent: calling this again on
    text with no block present returns the input unchanged with removed=False.
    """
    if not existing_text:
        return existing_text or "", False
    pattern = re.compile(
        r"\n*" + re.escape(marker_start) + r".*?" + re.escape(marker_end) + r"\n?",
        re.DOTALL,
    )
    new_text, count = pattern.subn("", existing_text)
    return new_text, count > 0


def has_marker_block(existing_text, marker_start=MARKER_START, marker_end=MARKER_END):
    return bool(_marker_block_pattern(marker_start, marker_end).search(existing_text or ""))


# ---------------------------------------------------------------------------
# Shim body generators -- pure string builders, one per shell surface.
# ---------------------------------------------------------------------------

def _ps_quote(value):
    return "'" + str(value).replace("'", "''") + "'"


def build_powershell_body(claude_path, python_path, banner_py_path):
    """PowerShell `claude` function: invokes `banner.py --anim`, skips
    -p/--print, try/catch fails open to a plain launch if the banner step
    errors for any reason.

    fg-a10905: --anim is SELF-TIMED (a ~2.6s, 30-frame gleam sweep) -- the
    animation itself is the launch-visibility hold that fg-a10904's
    POST-BUILD FINDING established was needed (the Claude TUI wipes the
    console via an alternate screen buffer immediately on launch), so no
    separate Start-Sleep is needed alongside it any more.

    CRITICAL INVARIANT: python is invoked DIRECTLY here, never piped
    through `| Out-Host`. Piping captures stdout as objects and buffers it
    until the process exits, which defeats the animation's cursor-up +
    \\x1b[2K redraw loop (only the final frame would ever appear). `2>$null`
    alone (stderr-only redirection, no pipe) does not have this problem --
    stdout still streams straight to the console in real time.
    """
    lines = ["function claude {"]
    lines.append("    if (($args -notcontains '-p') -and ($args -notcontains '--print')) {")
    lines.append("        try {")
    if python_path and banner_py_path:
        lines.append(
            f"            & {_ps_quote(python_path)} {_ps_quote(str(banner_py_path))} "
            "--anim 2>$null"
        )
    else:
        lines.append("            # python/banner.py not resolved at install time; skipped.")
    lines.append("        } catch {}")
    lines.append("    }")
    if claude_path:
        lines.append(f"    & {_ps_quote(claude_path)} @args")
    else:
        lines.append("    & claude.exe @args  # claude CLI path not resolved at install time")
    lines.append("}")
    return "\n".join(lines)


def build_bash_body(claude_path, python_path, banner_py_path):
    """bash/zsh `claude` function equivalent to the PowerShell one.

    fg-a10905: invokes `banner.py --anim`, which is self-timed (~2.6s
    gleam sweep) -- the animation itself is the launch-visibility hold
    (the Claude TUI wipes the console on launch), so no separate sleep is
    needed any more. Lives inside the same -p/--print skip-guard as the
    banner (fg-a10904)."""
    lines = ["claude() {"]
    lines.append("    __forge_skip_banner=0")
    lines.append('    for __forge_arg in "$@"; do')
    lines.append('        case "$__forge_arg" in')
    lines.append("            -p|--print) __forge_skip_banner=1 ;;")
    lines.append("        esac")
    lines.append("    done")
    lines.append('    if [ "$__forge_skip_banner" -eq 0 ]; then')
    if python_path and banner_py_path:
        lines.append(f'        "{python_path}" "{banner_py_path}" --anim 2>/dev/null || true')
    else:
        lines.append("        : # python/banner.py not resolved at install time; skipped.")
    lines.append("    fi")
    lines.append("    unset __forge_skip_banner __forge_arg")
    if claude_path:
        lines.append(f'    command "{claude_path}" "$@"')
    else:
        lines.append('    command claude "$@"')
    lines.append("}")
    return "\n".join(lines)


def build_claude_bat(claude_path, python_path, banner_py_path):
    """cmd.exe shim: skips -p/--print, fails silent (2>nul) if python or
    banner.py is missing, calls the real claude.exe with an absolute path
    resolved at install time (never hardcoded).

    fg-a10905: invokes `banner.py --anim`, self-timed (~2.6s gleam sweep)
    inside the SAME FORGE_SKIP_BANNER guard used for the banner call itself
    -- the animation is now the launch-visibility hold fg-a10904's
    POST-BUILD FINDING established was needed (the Claude TUI wipes the
    console via an alternate screen buffer on launch), so the separate
    `ping` hold that used to live here is gone. -p/--print skip the guard
    entirely, so they get neither the banner nor the hold."""
    lines = ["@echo off", FORGE_BAT_TAG, "setlocal"]
    lines.append("set FORGE_SKIP_BANNER=0")
    lines.append("for %%A in (%*) do (")
    lines.append('    if /I "%%~A"=="-p" set FORGE_SKIP_BANNER=1')
    lines.append('    if /I "%%~A"=="--print" set FORGE_SKIP_BANNER=1')
    lines.append(")")
    lines.append('if "%FORGE_SKIP_BANNER%"=="0" (')
    if python_path and banner_py_path:
        lines.append(f'    "{python_path}" "{banner_py_path}" --anim 2>nul')
    lines.append(")")
    if claude_path:
        lines.append(f'"{claude_path}" %*')
    else:
        lines.append("claude.exe %*")
    lines.append("endlocal")
    return "\r\n".join(lines) + "\r\n"


def build_autorun_cmd(claude_bat_path):
    """The AutoRun target: defines the `claude` doskey macro. doskey macros
    only expand for an *interactive* cmd session, so `cmd /c ...` and
    scripts invoking `claude` stay clean without any extra guard."""
    lines = [
        "@echo off",
        FORGE_AUTORUN_TAG,
        f'doskey claude=call "{claude_bat_path}" $*',
    ]
    return "\r\n".join(lines) + "\r\n"


def build_autorun_invocation(autorun_cmd_path):
    return f'"{autorun_cmd_path}"'


# ---------------------------------------------------------------------------
# AutoRun chaining -- pure logic, no registry I/O, fully unit-testable.
# ---------------------------------------------------------------------------

def compute_new_autorun(existing_value, our_invocation):
    """Idempotent AutoRun chaining. existing_value is the current AutoRun
    string (None/"" if unset). If our_invocation already appears anywhere in
    existing_value, returns it unchanged (idempotent re-install). Otherwise
    chains "existing & ours"."""
    existing_value = existing_value or ""
    if not existing_value.strip():
        return our_invocation
    if our_invocation in existing_value:
        return existing_value
    return existing_value.rstrip() + " & " + our_invocation


def compute_autorun_after_uninstall(existing_value, our_invocation):
    """Unchain exactly our segment from AutoRun, leaving any other chained
    command untouched. Returns the new value, or None if nothing is left
    (caller should delete the registry value entirely)."""
    if not existing_value:
        return None
    result = existing_value
    for variant in (" & " + our_invocation, our_invocation + " & ", our_invocation):
        if variant in result:
            result = result.replace(variant, "", 1)
            break
    result = result.strip()
    return result or None


# ---------------------------------------------------------------------------
# Registry access -- the ONLY functions that touch HKCU. Import-guarded
# (winreg is None off Windows) and swappable via get_fn/set_fn params on the
# orchestration functions below, so tests never touch the real registry.
# ---------------------------------------------------------------------------

def get_autorun_value():
    if winreg is None:
        raise RuntimeError("winreg is not available on this platform")
    try:
        with winreg.OpenKey(winreg.HKEY_CURRENT_USER, REGISTRY_KEY_PATH) as key:
            value, _ = winreg.QueryValueEx(key, REGISTRY_VALUE_NAME)
            return value
    except FileNotFoundError:
        return None


def set_autorun_value(value):
    if winreg is None:
        raise RuntimeError("winreg is not available on this platform")
    if value is None:
        delete_autorun_value()
        return
    # CREATE the key if absent (New-Item equivalent) then set the value.
    with winreg.CreateKeyEx(winreg.HKEY_CURRENT_USER, REGISTRY_KEY_PATH) as key:
        winreg.SetValueEx(key, REGISTRY_VALUE_NAME, 0, winreg.REG_SZ, value)


def delete_autorun_value():
    if winreg is None:
        raise RuntimeError("winreg is not available on this platform")
    try:
        with winreg.OpenKey(winreg.HKEY_CURRENT_USER, REGISTRY_KEY_PATH, 0,
                             winreg.KEY_SET_VALUE) as key:
            winreg.DeleteValue(key, REGISTRY_VALUE_NAME)
    except FileNotFoundError:
        pass


def install_autorun(autorun_cmd_path, get_fn=get_autorun_value, set_fn=set_autorun_value):
    """Install/adopt/chain the AutoRun macro. Returns (action, new_value)
    where action is "installed" | "chained" | "unchanged"."""
    our_invocation = build_autorun_invocation(autorun_cmd_path)
    existing = get_fn()
    new_value = compute_new_autorun(existing, our_invocation)
    if new_value == (existing or ""):
        return "unchanged", existing
    set_fn(new_value)
    action = "installed" if not existing or not existing.strip() else "chained"
    return action, new_value


def uninstall_autorun(autorun_cmd_path, get_fn=get_autorun_value, set_fn=set_autorun_value):
    """Remove exactly our AutoRun segment, unchaining carefully. Returns
    (action, new_value) where action is "removed" | "unchained" | "absent"."""
    our_invocation = build_autorun_invocation(autorun_cmd_path)
    existing = get_fn()
    if not existing or our_invocation not in existing:
        return "absent", existing
    new_value = compute_autorun_after_uninstall(existing, our_invocation)
    set_fn(new_value)
    return ("removed" if new_value is None else "unchained"), new_value


# ---------------------------------------------------------------------------
# File-target install/uninstall/status -- PowerShell profiles, bash/zsh rc.
# ---------------------------------------------------------------------------

def install_into_file(path, body, marker_start=MARKER_START, marker_end=MARKER_END):
    path = Path(path)
    existing = path.read_text(encoding="utf-8") if path.is_file() else ""
    new_text, action = upsert_marker_block(existing, body, marker_start, marker_end)
    if action != "unchanged":
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(new_text, encoding="utf-8", newline="\n")
    return action


def uninstall_from_file(path, marker_start=MARKER_START, marker_end=MARKER_END):
    path = Path(path)
    if not path.is_file():
        return "absent"
    existing = path.read_text(encoding="utf-8")
    new_text, removed = remove_marker_block(existing, marker_start, marker_end)
    if removed:
        path.write_text(new_text, encoding="utf-8", newline="\n")
        return "removed"
    return "absent"


def status_of_file(path, marker_start=MARKER_START, marker_end=MARKER_END):
    path = Path(path)
    if not path.is_file():
        return "no such file"
    text = path.read_text(encoding="utf-8")
    return "installed" if has_marker_block(text, marker_start, marker_end) else "not installed"


# ---------------------------------------------------------------------------
# User-level orn-motd dedupe -- the plugin now ships its own welcome-area
# hook (hooks/hooks.json -> hooks/scripts/orn-motd.sh, registered
# unconditionally as part of the plugin), which does exactly what the
# 2026-07-18 hand-wired fix did: emit {"systemMessage": ...} from
# banner.py --hook. If a user-level SessionStart entry referencing
# 'orn-motd' (e.g. the hand fix at C:\Users\<user>\.claude\orn-motd.py,
# wired into ~/.claude/settings.json) survives alongside the now-active
# plugin hook, the örn art prints TWICE every session start. This detects
# and deregisters exactly that duplicate. It never deletes the underlying
# script file it didn't create -- only the settings.json wiring, so the
# change is restore-safe (a user who wants the old hand-wired hook back
# can always re-add the entry by hand; the file itself is left untouched).
# ---------------------------------------------------------------------------

USER_SETTINGS_PATH = Path.home() / ".claude" / "settings.json"


def find_orn_motd_hook_indices(hooks_section):
    """Pure: given the 'hooks' dict from a settings.json-shaped document
    (lifecycle -> list of matcher-groups -> list of hook entries), return a
    list of (lifecycle, group_index, hook_index) for every hook entry whose
    command references 'orn-motd'."""
    hits = []
    for lifecycle, groups in (hooks_section or {}).items():
        for gi, group in enumerate(groups or []):
            for hi, hook in enumerate((group or {}).get("hooks", []) or []):
                if "orn-motd" in hook.get("command", ""):
                    hits.append((lifecycle, gi, hi))
    return hits


def remove_orn_motd_hooks(settings_data):
    """Pure, no I/O: returns (new_settings_data, removed_count).

    Removes exactly the hook entries whose command references 'orn-motd'
    from settings_data["hooks"], pruning now-empty matcher-groups and
    now-empty lifecycle lists, and leaves every other hook (any lifecycle,
    any tool) and every other top-level settings.json key untouched.
    Idempotent: a second call on the already-cleaned data returns it
    unchanged with removed_count 0.
    """
    data = dict(settings_data) if settings_data else {}
    hooks = data.get("hooks")
    if not hooks:
        return data, 0

    removed = 0
    new_hooks = {}
    for lifecycle, groups in hooks.items():
        new_groups = []
        for group in groups or []:
            hook_list = (group or {}).get("hooks", []) or []
            kept = [h for h in hook_list if "orn-motd" not in h.get("command", "")]
            removed += len(hook_list) - len(kept)
            if kept:
                new_group = dict(group)
                new_group["hooks"] = kept
                new_groups.append(new_group)
            # else: the whole matcher-group was only the orn-motd entry -- drop it.
        if new_groups:
            new_hooks[lifecycle] = new_groups
        # else: the whole lifecycle had nothing left -- drop the key.

    if removed == 0:
        return data, 0

    new_data = dict(data)
    if new_hooks:
        new_data["hooks"] = new_hooks
    else:
        new_data.pop("hooks", None)
    return new_data, removed


def dedupe_user_level_orn_motd(settings_path=None, read_fn=None, write_fn=None):
    """Detect + deregister a hand-wired user-level SessionStart hook
    referencing 'orn-motd' from ~/.claude/settings.json (or an injected
    path/read_fn/write_fn triple, for tests -- mirrors the get_fn/set_fn
    registry-stub pattern used for AutoRun below). Only ever touches the
    settings.json wiring; never deletes the script file it points at.
    Returns a human-readable report line, same style as install_all()/
    uninstall_all()'s other per-surface lines.
    """
    path = Path(settings_path) if settings_path else USER_SETTINGS_PATH

    if read_fn is not None:
        data = read_fn()
    else:
        if not path.is_file():
            return "user-level orn-motd hook: none found (no ~/.claude/settings.json)"
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except Exception:
            return "user-level orn-motd hook: settings.json unreadable, skipped"

    new_data, removed = remove_orn_motd_hooks(data)
    if removed == 0:
        return "user-level orn-motd hook: none found (nothing to dedupe)"

    if write_fn is not None:
        write_fn(new_data)
    else:
        try:
            path.write_text(json.dumps(new_data, indent=2) + "\n", encoding="utf-8")
        except Exception:
            return (f"user-level orn-motd hook: found {removed} but could not "
                     "remove (settings.json not writable) -- remove it by hand "
                     "to avoid the örn art printing twice")

    plural = "y" if removed == 1 else "ies"
    return (f"user-level orn-motd hook: removed {removed} duplicate entr{plural} "
            "from ~/.claude/settings.json (the plugin's own welcome-area hook "
            "now covers this; the script file itself was left in place)")


# ---------------------------------------------------------------------------
# Shell-surface detection
# ---------------------------------------------------------------------------

def detect_powershell_profiles():
    """Ask each installed PowerShell host for its own $PROFILE -- never
    guess the Documents\\WindowsPowerShell layout by hand (OneDrive
    redirection, PS7 vs 5.1, CDXML host differences all move $PROFILE)."""
    profiles = []
    for exe in ("powershell", "pwsh"):
        if shutil.which(exe) is None:
            continue
        try:
            result = subprocess.run(
                [exe, "-NoProfile", "-Command", "$PROFILE"],
                capture_output=True, text=True, timeout=15,
            )
            value = result.stdout.strip()
            if result.returncode == 0 and value:
                profiles.append((exe, Path(value)))
        except Exception:
            continue
    return profiles


def detect_shell_rc_files():
    home = Path.home()
    candidates = [("bash", home / ".bashrc"), ("zsh", home / ".zshrc")]
    return [(shell, path) for shell, path in candidates if path.is_file()]


def default_shim_dir():
    return Path.home() / SHIM_DIRNAME


# ---------------------------------------------------------------------------
# Orchestration -- install / uninstall / status across every surface.
# ---------------------------------------------------------------------------

def install_all():
    report = []
    claude_path = resolve_claude_cli_path()
    python_path = resolve_python_interpreter()
    banner_py_path = resolve_banner_py_path()

    if claude_path is None:
        report.append("claude CLI not found on PATH -- aborting install "
                       "(nothing written).")
        return report

    ps_body = build_powershell_body(claude_path, python_path, banner_py_path)
    ps_profiles = detect_powershell_profiles()
    for shell, profile_path in ps_profiles:
        action = install_into_file(profile_path, ps_body)
        report.append(f"{shell} profile ({profile_path}): {action}")
    if not ps_profiles:
        report.append("no PowerShell host found on PATH -- skipped.")

    bash_body = build_bash_body(claude_path, python_path, banner_py_path)
    rc_files = detect_shell_rc_files()
    for shell, rc_path in rc_files:
        action = install_into_file(rc_path, bash_body)
        report.append(f"{shell} rc ({rc_path}): {action}")
    if not rc_files:
        report.append("no ~/.bashrc or ~/.zshrc found -- skipped (nothing to adopt).")

    if os.name == "nt":
        shim_dir = default_shim_dir()
        shim_dir.mkdir(parents=True, exist_ok=True)
        claude_bat = shim_dir / CLAUDE_BAT_NAME
        autorun_cmd = shim_dir / AUTORUN_CMD_NAME
        claude_bat.write_text(build_claude_bat(claude_path, python_path, banner_py_path),
                               encoding="utf-8", newline="")
        autorun_cmd.write_text(build_autorun_cmd(claude_bat), encoding="utf-8", newline="")
        report.append(f"cmd shim written: {claude_bat}")
        if winreg is not None:
            action, _ = install_autorun(autorun_cmd)
            report.append(f"cmd AutoRun (HKCU\\{REGISTRY_KEY_PATH}): {action}")
        else:
            report.append("cmd AutoRun: winreg unavailable, skipped.")
    else:
        report.append("cmd.exe shim: not on Windows, skipped.")

    report.append('Note: Win+R "claude" (Run dialog) bypasses every shim above '
                   "-- out of scope, not wrapped.")

    # The plugin's own welcome-area hook (hooks/scripts/orn-motd.sh) is
    # shipped and active as soon as the plugin is installed -- independent
    # of this launcher-shim install. If a hand-wired user-level duplicate
    # is still registered, it would double-print the örn art every session.
    report.append(dedupe_user_level_orn_motd())
    return report


def uninstall_all():
    report = []
    for shell, profile_path in detect_powershell_profiles():
        action = uninstall_from_file(profile_path)
        report.append(f"{shell} profile ({profile_path}): {action}")

    for shell, rc_path in detect_shell_rc_files():
        action = uninstall_from_file(rc_path)
        report.append(f"{shell} rc ({rc_path}): {action}")

    if os.name == "nt":
        shim_dir = default_shim_dir()
        claude_bat = shim_dir / CLAUDE_BAT_NAME
        autorun_cmd = shim_dir / AUTORUN_CMD_NAME
        if winreg is not None:
            action, _ = uninstall_autorun(autorun_cmd)
            report.append(f"cmd AutoRun (HKCU\\{REGISTRY_KEY_PATH}): {action}")
        for shim_file, tag in ((claude_bat, FORGE_BAT_TAG), (autorun_cmd, FORGE_AUTORUN_TAG)):
            if shim_file.is_file():
                try:
                    text = shim_file.read_text(encoding="utf-8", errors="ignore")
                except OSError:
                    text = ""
                if tag in text:
                    shim_file.unlink()
                    report.append(f"cmd shim removed: {shim_file}")
                else:
                    report.append(f"cmd shim ({shim_file}): not forge-authored, left alone")
            else:
                report.append(f"cmd shim ({shim_file}): absent")

    # Uninstalling the launcher shim does not affect the plugin's own
    # welcome-area hook (hooks/scripts/orn-motd.sh) -- that stays wired via
    # hooks.json regardless. A stale user-level duplicate would still
    # double-print the örn art, so dedupe here too.
    report.append(dedupe_user_level_orn_motd())
    return report


def status_all():
    report = []
    for shell, profile_path in detect_powershell_profiles():
        report.append(f"{shell} profile ({profile_path}): {status_of_file(profile_path)}")
    for shell, rc_path in detect_shell_rc_files():
        report.append(f"{shell} rc ({rc_path}): {status_of_file(rc_path)}")
    if os.name == "nt":
        shim_dir = default_shim_dir()
        claude_bat = shim_dir / CLAUDE_BAT_NAME
        autorun_cmd = shim_dir / AUTORUN_CMD_NAME
        report.append(f"cmd shim ({claude_bat}): "
                       f"{'present' if claude_bat.is_file() else 'absent'}")
        if winreg is not None:
            existing = get_autorun_value()
            our_invocation = build_autorun_invocation(autorun_cmd)
            if existing and our_invocation in existing:
                state = "installed"
            elif existing:
                state = f"AutoRun set to something else: {existing!r}"
            else:
                state = "not installed"
            report.append(f"cmd AutoRun (HKCU\\{REGISTRY_KEY_PATH}): {state}")
        else:
            report.append("cmd AutoRun: winreg unavailable, cannot check.")
    return report


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv=None):
    parser = argparse.ArgumentParser(
        prog="banner_install.py",
        description="Install/uninstall/status the Forge banner launcher shim.",
    )
    parser.add_argument("action", choices=["install", "uninstall", "status"])
    args = parser.parse_args(argv)

    if args.action == "install":
        lines = install_all()
    elif args.action == "uninstall":
        lines = uninstall_all()
    else:
        lines = status_all()

    for line in lines:
        print(line)
    return 0


if __name__ == "__main__":
    sys.exit(main())
